name: APPS
on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo
        required: true
        default: 'https://github.com/feiyu666666/update'
    branches:
      - main
  schedule:
    - cron: '50 3 * * *'
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  apps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: feiyu666666/update
          token: ${{ secrets.TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: process
        env:
            MYURL: ${{ secrets.url }}
            MyAuthorization: ${{ secrets.myauthorization }}
        run: |
          python -c "import requests
          import json
          import os
          d={}
          url=os.environ['MYURL']
          MyAuthorization=os.environ['MyAuthorization']
          headers={'Authorization':MyAuthorization}
          r=requests.get(url+'/steam', headers=headers).text
          myd=json.loads(r)
          for i in myd['results']:
              d[i['username']]=[i['password'],None]
          r=requests.get(url+'/steam2', headers=headers).text
          myd=json.loads(r)
          for i in myd['results']:
              d[i['username']]=[i['password'],None]
          r=requests.get(url+'/mysteamlib', headers=headers).text
          myd=json.loads(r)
          for i in myd['results']:
              d[i['username']]=[i['password'],None]
          r=requests.get(url+'/feilifeili', headers=headers).text
          myd=json.loads(r)
          for i in myd['results']:
              d[i['username']]=[i['password'],None]
          print("*"*10,len(d),"*"*10)
          with open('/u.json','w') as f:
              f.write(json.dumps(d))"
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          python main.py -i -P -k ${{ secrets.KEY }}
          python apps.py -r ${{ github.event.inputs.repo || 'https://github.com/feiyu666666/update' }} -o data
          python push.py
